import {
    LayoutDashboard,
    Route,
    PlusCircle,
    Calendar,
    Settings,
    User,
    LogOut,
    Car,
    History,
    HelpCircle,
} from 'lucide-react';
import { SidebarData } from '@/components/shared/Sidebar/types';

export const adminSidebarData: SidebarData = {
    navItems: [
        {
            href: '/',
            label: 'adminNavigation.dashboard',
            description: 'adminNavigation.dashboardDescription',
            icon: LayoutDashboard,
            groupId: 'general',
            priority: 1,
            match: (url) => url === '/',
            matchMode: 'exact',
        },
        {
            href: '/ride-management',
            label: 'adminNavigation.rideManagement',
            description: 'adminNavigation.rideManagementDescription',
            icon: Route,
            groupId: 'rides',
            priority: 1,
            match: (url) => url.startsWith('/ride-management'),
            matchMode: 'ancestor',
        },
        {
            href: '/ride-management/new',
            label: 'adminNavigation.newRide',
            description: 'adminNavigation.newRideDescription',
            icon: PlusCircle,
            groupId: 'rides',
            priority: 2,
            match: (url) => url === '/ride-management/new' || url.startsWith('/ride-management/new/'),
            matchMode: 'exact',
        },
        {
            href: '/rides/booking',
            label: 'customerNavigation.bookRide',
            description: 'customerNavigation.bookRideDescription',
            icon: PlusCircle,
            groupId: 'rides',
            priority: 3,
            match: (url) => url === '/rides/booking' || url.startsWith('/rides/booking/'),
            matchMode: 'exact',
        },
        {
            href: '/rides',
            label: 'customerNavigation.myBookings',
            description: 'customerNavigation.myBookingsDescription',
            icon: Calendar,
            groupId: 'rides',
            priority: 4,
            match: (url) => url === '/rides' || (url.startsWith('/rides/') && !url.startsWith('/rides/booking')),
            matchMode: 'exact',
        },
    ],
    navGroups: [
        {
            id: 'general',
            label: 'adminNavigation.general',
            icon: LayoutDashboard,
            priority: 1,
        },
        {
            id: 'rides',
            label: 'adminNavigation.rides',
            icon: Route,
            priority: 2,
        },
    ],
    utilityItems: [
        {
            href: '/settings',
            label: 'adminNavigation.settings',
            icon: Settings,
            type: 'link',
        },
        {
            href: '/profile',
            label: 'adminNavigation.profile',
            icon: User,
            type: 'link',
        },
        {
            label: 'language',
            icon: User,
            type: 'dropdown',
        },
        {
            label: 'adminNavigation.signOut',
            icon: LogOut,
            type: 'action',
            action: 'signOut',
        },
    ],
    brandTitle: 'adminNavigation.brandTitle',
    brandSubtitle: 'adminNavigation.brandSubtitle',
};
