name: CI Full Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '24.7.0'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'false'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  tests-unit:
    uses: ./.github/workflows/tests-unit.yml
    secrets: inherit
    needs: [build]
  
  tests-rides:
    uses: ./.github/workflows/tests-rides.yml
    secrets: inherit
    needs: [build]

  tests-auth:
    uses: ./.github/workflows/tests-auth.yml
    secrets: inherit
    needs: [build]

  # Job final qui vérifier que tout a passé
  all-tests:
    name: All Tests Passed
    runs-on: ubuntu-latest
    needs: [build, tests-unit, tests-rides, tests-auth]
    if: always()
    
    steps:
      - name: Check all jobs succeeded
        run: |
          echo "Build: ${{ needs.build.result }}"
          echo "Unit Tests: ${{ needs.tests-unit.result }}"
          echo "Auth Tests: ${{ needs.tests-auth.result }}"
          echo "Rides Tests: ${{ needs.tests-rides.result }}"
          
          if [ "${{ needs.build.result }}" != "success" ] || \
             [ "${{ needs.tests-unit.result }}" != "success" ] || \
             [ "${{ needs.tests-auth.result }}" != "success" ] || \
             [ "${{ needs.tests-rides.result }}" != "success" ]; then
            echo "❌ Certains jobs ont échoué"
            exit 1
          else
            echo "✅ Tous les jobs ont réussi"
          fi